CREATE TABLE `Teams` (
  `yearID` varchar(4) NOT NULL,
  `lgID` text,
  `teamID` varchar(3) NOT NULL,
  `franchID` text,
  `divID` text,
  `Rank` text,
  `G` text,
  `Ghome` text,
  `W` text,
  `L` text,
  `DivWin` text,
  `WCWin` text,
  `LgWin` text,
  `WSWin` text,
  `R` text,
  `AB` text,
  `H` text,
  `2B` text,
  `3B` text,
  `HR` text,
  `BB` text,
  `SO` text,
  `SB` text,
  `CS` text,
  `HBP` text,
  `SF` text,
  `RA` text,
  `ER` text,
  `ERA` text,
  `CG` text,
  `SHO` text,
  `SV` text,
  `IPouts` text,
  `HA` text,
  `HRA` text,
  `BBA` text,
  `SOA` text,
  `E` text,
  `DP` text,
  `FP` text,
  `name` text,
  `park` text,
  `attendance` text,
  `BPF` text,
  `PPF` text,
  `teamIDBR` text,
  `teamIDlahman45` text,
  `teamIDretro` text,
  PRIMARY KEY (`yearID`,`teamID`),
  KEY `teamid_idx` (`teamID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
