CREATE TABLE `Batting` (
  `playerID` varchar(12) NOT NULL,
  `yearID` varchar(4) NOT NULL,
  `stint` varchar(1) NOT NULL,
  `teamID` varchar(3) NOT NULL,
  `lgID` text,
  `G` text,
  `AB` text,
  `R` text,
  `H` text,
  `2B` text,
  `3B` text,
  `HR` text,
  `RBI` text,
  `SB` text,
  `CS` text,
  `BB` text,
  `SO` text,
  `IBB` text,
  `HBP` text,
  `SH` text,
  `SF` text,
  `GIDP` text,
  PRIMARY KEY (`playerID`,`yearID`,`stint`),
  KEY `FK_teams` (`teamID`),
  KEY `FK_years` (`yearID`),
  CONSTRAINT `FK_player` FOREIGN KEY (`playerID`) REFERENCES `people` (`playerid`),
  CONSTRAINT `FK_teams` FOREIGN KEY (`teamID`) REFERENCES `teams` (`teamid`),
  CONSTRAINT `FK_years` FOREIGN KEY (`yearID`) REFERENCES `teams` (`yearid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
