CREATE TABLE `Fielding` (
  `playerID` varchar(12) NOT NULL,
  `yearID` varchar(4) NOT NULL,
  `stint` varchar(1) NOT NULL,
  `teamID` varchar(3) NOT NULL,
  `lgID` text,
  `POS` varchar(2) NOT NULL,
  `G` int(11) DEFAULT NULL,
  `GS` int(11) DEFAULT NULL,
  `InnOuts` int(11) DEFAULT NULL,
  `PO` int(11) DEFAULT NULL,
  `A` int(11) DEFAULT NULL,
  `E` int(11) DEFAULT NULL,
  `DP` int(11) DEFAULT NULL,
  `PB` int(11) DEFAULT NULL,
  `WP` int(11) DEFAULT NULL,
  `SB` int(11) DEFAULT NULL,
  `CS` int(11) DEFAULT NULL,
  `ZR` int(11) DEFAULT NULL,
  PRIMARY KEY (`playerID`,`yearID`,`stint`,`POS`),
  KEY `FK-field-year` (`yearID`),
  KEY `FK-field-team` (`teamID`),
  CONSTRAINT `FK-field-player` FOREIGN KEY (`playerID`) REFERENCES `people` (`playerid`),
  CONSTRAINT `FK-field-team` FOREIGN KEY (`teamID`) REFERENCES `teams` (`teamid`),
  CONSTRAINT `FK-field-year` FOREIGN KEY (`yearID`) REFERENCES `teams` (`yearid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
